[package]
name = "game-test"
version = "0.1.0"
authors = ["Niklas Larsson <niklaslarsson95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_engine = "1.1.0"
rand = "*"